version: '2'

# Purpose is to test compatibility in Python 3.9
# TODO: add tests
# Brings up two machines, both with python 3.9
# Database by SQLITE
# Config settings copied from install

services:
  bots39_1:
    build:
      context: .
      dockerfile: ./compose/bots_py34/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
  bots39_2:
    build:
      context: .
      dockerfile: ./compose/bots_py27/Dockerfile
    ports:
      - "0.0.0.0:8081:8080"
